### PR TITLE
Extension5

### PR DESCRIPTION
**Pull request by aorzelskiGH**
Add common device classes for comparisons in HA
Add register circulation temp 5027

### CODE REVIEW

**Comment by avanc** [comment]
5131 (Heizwasser Temp) ist not working on my side. It is always 300°C. "Heizwasser Soll" is working as expected. Any hint how I can debug it?
I have the same problem with "Zirkulation temp", it is also 300°C.

**Comment by avanc** [comment]
Thanks for the details. I also have the WKF 130.
I saw that the values are also 300 which are coming via MQTT, I have to dig deeper.

You diagram is also very interesting, I also was curious, how precise the internal power measurements are. It looks quite the same compared to your shelly output.
And also how often the compressor starts. In my setup it is roughly every hour, which I think is to often...

I you are interested in additional values, I integrated several energy meters:
https://github.com/avanc/remko_mqtt-ha/commit/e16af87ea144ea2b660022ea2e73347bab146215

**Comment by mkrusemark** [comment]
Would you mind merging the open pull requests.

**Comment by Altrec** [comment]
New registries can be added individually and don't (all) have to be added to the source code.

**Pull request closed without merging**
